baseURL = "/"
languageCode = "en-us"


[params]
footerContent= "End Impunity"
menuButtonText= "Learn More"
SiteLogo = "/IJM_Logo_Horizontal_White_ForWeb.png"


[[menu.main]]
Name = "About"
url = "/about"


